package com.freshbooks.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Some URLs that someone can browse to in order
 * to view or edit something.
 * 
 * This is always generated by the FreshBooks service.
 */
@XStreamAlias("links")
public class Links implements Serializable {
    private static final long serialVersionUID = -5881895138147227417L;
    
    private String view;
    @XStreamAlias("client_view")
    private String clientView;
    private String edit;
    public String getView() {
        return view;
    }
    public void setView(String view) {
        this.view = view;
    }
    public String getClientView() {
        return clientView;
    }
    public void setClientView(String clientView) {
        this.clientView = clientView;
    }
    public String getEdit() {
        return edit;
    }
    public void setEdit(String edit) {
        this.edit = edit;
    }
    
}
