package com.freshbooks.model;

import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Some URLs that someone can browse to in order
 * to view or edit something.
 * 
 * This is always generated by the FreshBooks service.
 */
@XStreamAlias("links")
public class Links implements Serializable {
    private static final long serialVersionUID = -5881895138147227417L;
    
    private String view;
    @XStreamAlias("client_view")
    private String clientView;
    private String edit;
    public String getView() {
        return view;
    }
    public void setView(String view) {
        this.view = view;
    }
    public String getClientView() {
        return clientView;
    }
    public void setClientView(String clientView) {
        this.clientView = clientView;
    }
    public String getEdit() {
        return edit;
    }
    public void setEdit(String edit) {
        this.edit = edit;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof Links))
            return false;
        Links other = (Links) obj;
        if (clientView == null) {
            if (other.clientView != null)
                return false;
        } else if (!clientView.equals(other.clientView))
            return false;
        if (edit == null) {
            if (other.edit != null)
                return false;
        } else if (!edit.equals(other.edit))
            return false;
        if (view == null) {
            if (other.view != null)
                return false;
        } else if (!view.equals(other.view))
            return false;
        return true;
    }
    
}
